### ISSUE TITLE
aliases ? what about some fancy short names 

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/Topos#5]
for the filters
`lpf` `hpf` `bpf` 
with
`lpq` `hpq` `bpq`

i really believe it could be more logical to have a common `resonance` or `res` parameter fir the three types of filter, and if you want some precise controls you can use `lpq` `hpq` `bpq`

delay
`delayfb` `delayt` `delay`

velocity 
`vel`

euclid
`eu`

control_change()
`cc()`

program_change()
`pc()`

sysex()
`sy()`

**Comment by Bubobubobubobubo** [comment]
Done.
