### ISSUE TITLE
better filters ?

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/Topos#6]
`resonance` doesn't seems to have a real effect on filters, or doesn't sounds really nice, 
What are the different filter slopes/what order are they?

**Comment by Bubobubobubobubo** [comment]
The value of `resonance` is a number between 0 and 50. It should be possible to implement better filters by patching [Superdough](https://www.npmjs.com/package/superdough).

**Comment by Bubobubobubobubo** [comment]
Fixed
