### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by lutangar** [Bubobubobubobubo/topos#77]
Would be great to have code completion :
- to learn the synthax directy from the editor
- to go quicker while avoiding short function name

**Comment by Bubobubobubobubo** [comment]
Autocompletion now has its own branch: dbd7721. Just added basic autoCompletion support, now working on styling it a bit more :)

**Comment by Bubobubobubobubo** [comment]
<img width="470" alt="screenshot 2023-10-29 à 22 50 49" src="https://github.com/Bubobubobubobubo/topos/assets/45191785/5ffcaaed-90e2-4653-8248-8faa23445f51">

CSS needs to be adapted a tiny bit 😄

**Comment by Bubobubobubobubo** [comment]
I only installed a very barebones completion system. It does not detect the difference between `beat` and `.beat` but descriptions are generic and Array Prototype extensions are doing the same thing as the base function.

**Comment by Bubobubobubobubo** [comment]
This is now merged, with an option to turn it on/off. Closing. You can re-open another issue if you want to take this further!
